version: "3.8"
services:
  database:
    image: postgres:latest
    environment:
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "example"
    ports:
      - "5432:5432"
    volumes:
      - postgres_database:/var/lib/postgresql/data
volumes:
  postgres_database:
