version: "3.8"
services:
  postgresql:
    container_name: postgresql
    image: postgres:latest
    environment:
      POSTGRES_USER: "admin_user"
      POSTGRES_PASSWORD: "admin_pass"
      POSTGRES_DATABASE: "database_name"
    ports:
      - "5432:5432"
    volumes:
      - postgres:/var/lib/postgresql/data
volumes:
  postgres:
